redis.key.pre-register-info=pre_register_info:%s
redis.key.pre-register-code=preRegister:%s
redis.key.forget-password-code=forget_password_code:%s
redis.key.logout-token=logout:%s
redis.key.user-info=user_info:%s
redis.key.word-with-trans=word_with_trans:%s
redis.key.word-without-trans=word_without_trans:%s
redis.key.current-review=current_review:%s:%s:%s
redis.key.review-quiz=review_quiz:v2:%s:%s
redis.key.current-review-wrong=current_review_wrong:%s
redis.key.reading-quiz=reading_quiz:%s
redis.ttl.pre-register-minutes=5
redis.ttl.forget-password-minutes=5
redis.ttl.logout-days=1
redis.ttl.current-review-hours=2
redis.ttl.review-quiz-hours=2
redis.ttl.current-review-wrong-hours=2
